EMART_pp/EMART_pp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('profile/',V2.update_profile),
    path('',include('home.urls')),
    path('signup/',include('signup.urls')),
    
]

EMART_pp/home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seller/', views.Seller_view),
    path('product/', views.Product_view),
    path('productshow/', views.product_show),
    path('sign_up1/',views.SignUp1),
    path('',views.Home_view),
    path('login/',views.login),
    path('detail/<int:id>/',views.detail),
    path('add_to_cart/',views.Cartview),
    path("update/<id>/", views.update),
    path("delete/<id>/", views.delete),
    path("remove_cart/<id>/", views.remove_cart),
    path("login/", views.login),
    path("logout/", views.logout),
    path("show_cart/", views.show_add_to_cart),
    path("success/", views.success),
    path("buy_history/", views.buy_history),
    path("search/", views.search),


]

EMART_pp/signup/urls.py
from django.contrib import admin
from django.urls import path,include
from signup import views

urlpatterns = [
    path('sign_up/',views.sign_up)
]

EMART_pp/home/models.py
from django.db import models

# Create your models here.
class Usermode(models.Model):
    user_name = models.CharField(max_length=30)
    user_mob_no = models.BigIntegerField()
    alternate_No= models.BigIntegerField()
    user_email = models.EmailField()
    user_address = models.CharField(max_length=60)

class Seller_Model(models.Model):
    Seller_id = models.CharField(max_length=30)
    company_business_name = models.CharField(max_length=30)
    Seller_name = models.CharField(max_length=30)
    Seller_mob_no = models.BigIntegerField()
    Seller_email = models.EmailField()
    Seller_address = models.CharField(max_length=60)

class Product_details(models.Model):
    product_name = models.CharField(max_length=30)
    Product_brand = models.CharField(max_length=30)
    Product_category = models.CharField(max_length=30)
    product_cost = models.IntegerField()
    prod_quantity = models.IntegerField(default=1)
    product_image = models.ImageField(upload_to='static/media/')
    product_releasedate = models.DateField()
    product_description = models.CharField(max_length=60)
    Seller_mob_no = models.BigIntegerField(default=1)

class Cart1(models.Model):
    phone=models.CharField(max_length=10)
    Product_brand=models.ForeignKey(Product_details,on_delete=models.CASCADE)
    product_image=models.ImageField(null=True,blank=True)
    quantity=models.PositiveIntegerField(default=1)
    product_cost=models.IntegerField(default=0)



class User_Model(models.Model):
    username=models.CharField(max_length=50)
    password = models.CharField(max_length = 20)
    phone=models.CharField(max_length=10)
    email_id = models.EmailField()
    address_field = models.CharField(max_length=50)
    dob = models.DateField()
    def register(self):
        self.save()
    def isExists(self):
        if User_Model.objects.filter(phone=self.phone):
            return True
        else:
            False

STATUS_CHOICE = (
    ('Accepted','Accepted'),
    ('Packed','Packed'),
    ('On the Way','On The Way'),
    ('Delivered','Delivered'),
    ('Cancel','Cancel')
 )
class order_details(models.Model):
    user=models.IntegerField(default=True)
    Product_name= models.CharField(max_length=250)
    image=models.ImageField(null=True,blank=True)
    Qty=models.PositiveIntegerField(default=1)
    price=models.IntegerField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=50,default='pendding',choices=STATUS_CHOICE)


class sales_detailss(models.Model):
    record_date = models.DateField()
    buyer_id = models.BigIntegerField()
    product_id = models.IntegerField()
    prd_quant = models.IntegerField()

EMART_pp/signup/models.py
from django.db import models

# Create your models here.

EMART_pp/home/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,HttpResponse
from .form import Userform,Sellerform,Productform
from .models import Usermode,Seller_Model,User_Model, Product_details,Cart1,sales_detailss
from home import calc
from django.contrib import messages
from django.db.models import Q
from django.db import connection
from datetime import date
from itertools import chain#to join orm querysets
myconn = connection.cursor()
username= ''
switch = 'logout'
# Create your views here.
def SignUp1(r):
    obj=User_Model.objects.all()
    if r.method=='GET':
        return render(r,'home/Signup1.html')
    else:
        postdata=r.POST
        username=postdata.get('name')
        phone=postdata.get('phone')
        password=postdata.get('password')
        email_id=postdata.get('email_id')
        address_field=postdata.get('address_field')
        dob=postdata.get('dob')

        error_message=None
        value={
            'phone':phone,
            'username':username,
            'password':password,
            'email_id':email_id,
            'address_field':address_field,
            'dob':dob
        }

        customer=User_Model(username=username,password=password,email_id=email_id,address_field=address_field,
                          dob=dob,phone=phone)
        if(not username):
            error_message = "username is required"
        elif not phone:
            error_message = "phone No. is required"
        elif len(phone)!=10:
            error_message = "phone No. must be 10 digit"
        elif(not password):
            error_message = "Password is required"
        elif len(password)<8:
            error_message = "Password length is required"
        elif not email_id:
            error_message = "Email is required"
        elif not address_field:
            error_message = "Address is required"
        elif not dob:
            error_message = "Date Of Birth is required"
        elif '@' not in email_id or not email_id.endswith('.com'):
            error_message = "Email is invalid"
        elif customer.isExists():
            error_message = "Account already Exist"
            value={
            'phone':phone,
            'username':username,
            'password':password,
            'email_id':email_id,
            'address_field':address_field,
            'dob':dob
        }


        if not error_message:
            messages.success(r,'Congratulation !! Register Successfull')
            customer.register()
            return redirect('/')
        else:
            data={
                'error':error_message,
                'value':value

            }
            return render(r,'home/Signup1.html',data)



def login(r):
    if r.method=='GET':
        return render(r,'home/login.html')
    else:
        phone=r.POST.get('phone')
        password=r.POST.get('password')

        error_message=None
        value={
            'phone':int(phone),
            'password':password
        }


        customer=User_Model.objects.filter(phone=r.POST['phone'])
        if customer:
            passs = myconn.execute('select password from home_User_Model where phone = {}'.format(r.POST['phone']))
            for i in passs:
                if i[0] == r.POST['password']:    
                    r.session['phone']= int(phone)
                    return redirect('/')
            else:
                error_message= "Password is Invalid !!"

                data={
                    'error':error_message,
                    'value':value
                }
        else:
            error_message= "mobile No is Invalid !!"

            data={
                'error':error_message,
                'value':value
            }


        return render(r,'home/login.html',data)

def login_decor(f):
    def inner(r):
        if r.session.has_key('phone'):
            result = f(r)
            switch = 'logout'
            
            return result
        else:
            return HttpResponseRedirect('/login')
    return inner

def login_decor_id(f):    
    def inner(r, id):
        if r.session.has_key('phone'):
            result = f(r, id)
            switch = 'logout' 
            return result
        else:
            return HttpResponseRedirect('/login')
    return inner


def logout(r):
    del r.session['phone']
    return redirect('/login') 
        
@login_decor
def product_show(r):
    form = Product_details.objects.filter(Seller_mob_no=r.session['phone'])
    if len(form) != 0:
        user_name = ''.join([i.username for i in User_Model.objects.filter(phone=r.session['phone'])])
        return render(r,'home/product_show.html',{'form':form,'username':user_name, 'log':switch})

def Home_view(r):
    switch = 'login'
    username=''
    #data = Product_details.objects.order_by('-product_cost')[:4]
    data = Product_details.objects.all()
    if r.session.has_key('phone'):
        data1 = myconn.execute(f"select * from home_User_Model where phone = {r.session['phone']}")
        username = ''.join([i.username for i in data1])
        switch='logout'
    return render(r, 'home/cards.html',{'data':data, 'username':username, 'log':switch})
    


@login_decor
def Seller_view(r):
    form=Sellerform()
    if r.method=="POST":
        form=Sellerform(r.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/home')
    return render(r,'home/Sellerform.html',{'form':form, 'log':switch})
    

@login_decor
def delete(r,id):
    abc = Product_details.objects.get(id=id)
    abc.delete()
    return HttpResponseRedirect('/productshow')



@login_decor
def Product_view(r):
    form=Productform()
    if r.method=="POST":
        form=Productform(r.POST,r.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productshow')
    return render(r,'home/Productform.html',{'form':form,'num':int(r.session['phone']),'log':switch})



@login_decor
def update(r,id):
    abc= Product_details.objects.get(id=id)
    if r.method=="POST":
        form=Productform(r.POST, r.FILES, instance=abc)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productshow')
    return render(r,'home/update.html',{'abc':abc, 'log':switch})

@login_decor_id
def detail(r,id):
    totalitem=0
    form = Product_details.objects.get(id=id)
    Item_already_in_cart=False
    phone=r.session['phone']
    totalitem=len(Cart1.objects.filter(phone=phone))
    Item_already_in_cart=Cart1.objects.filter(Q(Product_brand=form.id) & Q(phone=phone)).exists()
    customer=User_Model.objects.filter(phone=phone)
    for c in customer:
        username=c.username
    data={
        'form':form,
        'Item_already_in_cart':Item_already_in_cart,
        'username':username,
        'totalitem':totalitem,
        'log':switch

    }
    if r.method=="POST":
        r.session['quant'] = r.POST['quant']
        
        return HttpResponseRedirect(f'/user/{form.id}')
    return render(r,'product_detail.html',data)    

@login_decor
def Cartview(r):
    phone=r.session['phone']
    product_id=r.GET.get('prod_id')
    username = ''.join([i.username for i in User_Model.objects.filter(phone=r.session['phone'])])
    product_name=Product_details.objects.get(id=product_id)
    product=Product_details.objects.filter(id=product_id)
    
    for p in product:
        product_image=p.product_image
        product_cost= p.product_cost
        Cart1(
                id=product_id,
                phone=phone,
                Product_brand=product_name,
                product_image=product_image,
                product_cost=product_cost
              ).save()
        return redirect(f"/detail/{product_id}")
        
@login_decor
def show_add_to_cart(r):
    form=Cart1.objects.filter(phone=r.session['phone'])
    user_name = ''.join([i.username for i in User_Model.objects.filter(phone=r.session['phone'])])
    data = [] #list of dictionaries of data
    print(username)
    for i in form:
        result = myconn.execute(f"select * from home_Product_details where id={i.Product_brand_id}")
        for i in result:
            data.append(i)
            
    if r.method=="POST":
        final_cost = 0
        total_quant = 0 
        payment_lists = []
        if '' not in r.POST.getlist('qun'):
            qun = [int(i) for i in r.POST.getlist('qun')]
            var2 = r.POST.getlist('p_id')
            for i,j in enumerate(var2):
                data = myconn.execute(f"Select product_cost from Home_Product_details where id = {j}")
                if qun[i] != 0:
                    costs = [i for i in data]
                    payment_details = {j:qun[i]}
                    payment_lists.append(payment_details)
                    myconn.execute(f"delete home_cart1 where id={j}" )
                    myconn.commit()
                    final_cost += costs[0][0]*qun[i]
                    total_quant += qun[i]
                    

        calculated_data={
        'fetched_quant':total_quant,
        'total': final_cost
        }
        r.session['cal_data'] = payment_lists
    
        
        return render(r, 'home/payments_method.html', calculated_data) 
    cart_data = {
            'form':data, 
            'log':switch, 
            'username':user_name
    }
    return render(r,'home/show_cart.html',cart_data)


@login_decor
def remove_cart(r,id):
    abc = Cart1.objects.get(id=id)
    abc.delete()
    return HttpResponseRedirect('/show_cart')
   


@login_decor      
def success(r):
    calculated_data = r.session['cal_data'] 
    print(calculated_data)
    # cal_data= [
        # {'1': 3}, 
        # {'2': 2}, 
        # {'3': 1}
    # ]
    
    for product_dict_keys in calculated_data:
        print(product_dict_keys)
        for prd_id, Quant in product_dict_keys.items():
            print("values", rec_no, product_id)
            

EMART_pp/signup/views.py
from django.shortcuts import render,HttpResponseRedirect
from .form import UserForm
# Create your views here.
def sign_up(r):
    if r.method == "POST":
        form = UserForm(r.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            return HttpResponseRedirect('/')
    return render(r, 'home/signup.html', {'form': UserForm})

EMART_pp/templates/home/Productform.html
<!DOCTYPE html>

<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">
    <title>Productform</title>
</head><hr>
<body>
<div class="container my-30" align="center">
<div class="shadow p-4">
<h1 align="center">Product Form </h1>
       <form method="post" enctype="multipart/form-data">
             <label for="id_product_name">Product name:</label>
             <input type="text" name="product_name" maxlength="30" required id="id_product_name">
             
             
           </p>

           
           <p>
             <label for="id_Product_brand">Product brand:</label>
             <input type="text" name="Product_brand" maxlength="30" required id="id_Product_brand">
             
             
           </p>

           
           <p>
             <label for="id_Product_category">Product category:</label>
             <input type="text" name="Product_category" maxlength="30" required id="id_Product_category">
             
             
           </p>

           
           <p>
             <label for="id_product_cost">Product cost:</label>
             <input type="number" name="product_cost" required id="id_product_cost">
             
             
           </p>

           
           <p>
             <label for="id_prod_quantity">Prod quantity:</label>
             <input type="number" name="prod_quantity" value="1" required id="id_prod_quantity">
             
             
           </p>

           
           <p>
             <label for="id_product_image">Product image:</label>
             <input type="file" name="product_image" accept="image/*" required id="id_product_image">
             
             
           </p>

           
           <p>
             <label for="id_product_releasedate">Product releasedate:</label>
             <input type="text" name="product_releasedate" required id="id_product_releasedate">
             
             
           </p>

           
           <p>
             <label for="id_product_description">Product description:</label>
             <input type="text" name="product_description" maxlength="60" required id="id_product_description">
             
             
           </p>

           
             <input type="hidden" name="Seller_mob_no" value="{{num}}" min="-9223372036854775808" max="9223372036854775807" required id="id_Seller_mob_no">
             
             
               
             
           
        {% csrf_token %}
      <input type="submit" value="submit">
      <a href="/" class="btn btn-success">Back</a><p></p>
    </form>
</div>
</div><hr>
</body>
{%endblock%}
</html>

EMART_pp/templates/home/Sellerform.html
<!DOCTYPE html>

<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">
    <title>Sellerform</title>
</head>
<body>
<h1 align="center">Seller Form </h1>
<div class="container" align="center">
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="submit">
    </form>
</div>

</body>
{%endblock%}
</html>

EMART_pp/templates/home/Signup1.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">
    <title>Customer SignUp</title>
</head>
<body>
<div class="Container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">

            <h3> Customer Signup</h3>
            <form method="POST" action="/sign_up1/" class="shadow p-5">
                {% if messages %}
                {% for Message in messages%}
                <p {% if message.tages%} class="alert alert-{{message.tags}} mb-5" {% endif%}>{{message}}</p>
                {%endfor%}
                {%endif%}
                {%csrf_token%}
                {%if error %}
                <div class="alert alert-danger" role="alert">{{error}}</div>
                {% endif%}

                <div class="form-group">
                    <labal for="" class="form-control-lg">Name</labal>
                    <input type="text" name="name" id="" value="{{value.name}}" class="form-contrl" placeholder="Enter Name"></input>
                </div>

                 <div class="form-group" >
                    <labal for="" class="form-control-lg">Mobile No.</labal>
                    <input type="text" name="phone" id="" value="{{value.phone}}" class="form-contrl" placeholder="Enter Mobile No."></input>
                </div>
                <div class="form-group" >
                    <labal for="" class="form-control-lg">Password</labal>
                    <input type="password" name="password" id="" value="{{value.password}}" class="form-contrl" placeholder="Enter Password No."></input>
                </div>
                <div class="form-group" >
                    <labal for="" class="form-control-lg">Email</labal>
                    <input type="text" name="email_id" id="" value="{{value.email_id}}" class="form-contrl" placeholder="Enter Password No."></input>
                </div>
                <div class="form-group" >
                    <labal for="" class="form-control-lg">Address</labal>
                    <input type="text" name="address_field" id="" value="{{value.email_id}}" class="form-contrl" placeholder="Enter Password No."></input>
                </div>
                <div class="form-group" >
                    <labal for="" class="form-control-lg">Date Of Birth</labal>
                    <input type="Date" name="dob" id="" value="{{value.dob}}" class="form-contrl" placeholder="Enter Password No."></input>
                </div>

                <div class="form-group pt-4">
                    <input class="btn btn-sm btn-info" type="submit" value="Signup"></input>
                </div>

                <div class="test-center text-primary fw-bold">
                <small> Existing User to EMART World ?</small>
                <a href="/login" class="text-danger"> Login</a>
                </div>

            </form>

        </div>

    </div>

</div>
</body>
{%endblock%}
</html>

EMART_pp/templates/home/buy_history.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
{%load static%}
<head>
    <meta charset="UTF-8">

    <title>Buy History</title>

</head><hr>
<body>
<style>
.row_span{
background-color:#cb86d1;
margin:auto;
}

</style>
<center>
    <div class="container my-50">
<div class="shadow p-5">
   <h1 align="center">Buy History</h1>
            <hr/>
            <hr/>
{% if form %}
<table class="table" id ="myTable" align="center">
<tbody>      
{% for Showuser2 in form %}
  {%for Showuser in Showuser2%}
  {%for date in dates%}

            <tr class="row_span">
            
                       
                  
             
            </tr>
            <tr>  
                                  
                        <td><img src="/{{Showuser.product_image}}" height="100px"/></td>
                        <td>
                           <p>Product Name : {{Showuser.product_name}}</p>                       
                           <p>Product Brand : {{Showuser.Product_brand}}</p> 
                           <p>Product Catagory : {{Showuser.Product_category}}<p>
                           <p>Product Price : {{Showuser.product_cost}}<p>
                           <p>Product Price : {{date}} <p>
                             
                        </td> 
                        <td>
                        <p>Product Discription : {{Showuser.product_description}}<p>
                        </td>
                        
                    
            </tr>
  {%endfor%}
 {%endfor%}  
{%endfor%}
</tbody>
    </table>
{%else%}
<h1> no data found</h1>
    <a href="/" class="btn btn-success">back</a>
{%endif%}


        <a href="/" class="btn btn-success">back</a>
</div>
    </center>

</body>
</div>
<script src="{% static 'js/calc_jquery.js'%}"></script>
{%endblock%}


</html>

EMART_pp/templates/home/cards.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head><hr>
<style>
.card-body{
width:100%;
position:absolute;
bottom:0px;
background-color:white;
opacity: 0.9;
}

</style>
<body>
<div class="row">

   {% for product in data %}
    <div class="card mx-auto mb-3" style="width: 15rem">
   <a href="/detail/{{product.id}}" class="btn">
        
            <div class="item">
               <img class="card-img-top" src="{{product.product_image.url}}"  alt="...">
            </div>
         
         
        <div class="card-body">
         <a class="card-title">{{product.product_name}}</a>
          <a>{{product.Product_brand}}</a><br>
          <a>Rs. {{product.product_cost}}</a>
         </div>
         
    </a>
    </div>
    
    
{%endfor%}
</div>


</body>
{%endblock%}
</html>

EMART_pp/templates/home/login.html
<!DOCTYPE html><html lang="en">
{%extends 'base.html'%}{%block baseblock%}
<head>    <meta charset="UTF-8">
    <title>Customer login</title></head>
<body><div class="Container"><center>
    <div class="row my-3">        
    <div class="col-sm-6 offset-sm-3">
            <h3> Customer login</h3>
            <form method="POST" action="/login/" class="shadow p-5">
                {%csrf_token%}                
                   {%if error %}
                     <div class="alert alert-danger" role="alert">{{error}}</div>                
                   {% endif%}
                 <div class="form-group" />
                    <labal for="" class="form-control-lg">Mobile No.</labal>                    
                    <input type="text" name="phone" value="{{value.phone}}" class="form-contrl" placeholder="Enter Mobile No."></input>
                    <p></p>
                    <labal for="" class="form-control-lg">Password.</labal> 
                    <input type="password" name="password" value="{{value.password}}" class="form-contrl" placeholder="Enter Mobile No."></input>
                </div>
                <div class="form-group pt-4">                    
                <input class="btn btn-sm btn-info" type="submit" value="login"></input>
                </div>
                <div class="test-center text-primary fw-bold">                <small>New User? Click Here to SignUp</small>
                <a href="/sign_up1" class="text-danger"> SignUp</a>                </div>
            </form>
        </div>
    </div></center>
</div>
</body>{%endblock%}
</html>

EMART_pp/templates/home/product_show.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">

    <title>Product_data</title>
</head><hr>
<body>

<center>
    <div class="container my-50">
<div class="shadow p-5>
<h1 align="center"> Product List</h1>

{% if form %}
<table class="table" align="center">

    <thead>
    <th>id</th>
<th> Name</th>
<th>Brand</th>
<th>Category</th>
<th>Cost</th>
<th>Release Date</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Image</th>
    </thead>
{% for Showuser in form %}
 <tr>
     <td>{{Showuser.id}}</td>
     <td>{{Showuser.product_name}}</td>
     <td>{{Showuser.Product_brand}}</td>
     <td>{{Showuser.Product_category}}</td>
     <td>{{Showuser.product_cost}}</td>
     <td>{{Showuser.product_releasedate}}</td>
     <td>{{Showuser.product_description}}</td>
     <td>{{Showuser.prod_quantity}}</td>
     <td><img src="{{Showuser.product_image.url}}" height="30px"></td>

     <td><a href="/update/{{Showuser.id}}" class="btn btn-success">update</a></td>
     <td><a href="/delete/{{Showuser.id}}" class="btn btn-danger">delete</a></td>


 </tr>
{%endfor%}
  <a href="/product/" class="btn btn-success">insert</a>
</table>
</div>
{%else%}
<h1> no data found</h1>
        <a href="/product/" class="btn btn-success">insert</a>
{%endif%}


    </center>

</body>
</div>
</div>
{%endblock%}

</html>

EMART_pp/templates/home/product_view.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-80">
    <title>Product_data</title>
</head>
<body>
<h1>welcome</h1>
<div class="container my-50">
  <div class="row">
    <div class="col-sm-60 text-center align self-center">
      <img src="{{showuser.product_image.url}}" alt="" class="img-fluid img-thumbnail">

    </div>

  </div>
</div>

</body>
{%endblock%}
</html>

EMART_pp/templates/home/profile.html
<!doctype html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
<h1>Welcome to profile</h1>
<!--    <div class="container pt-5">-->
<!--      <div class="d-flex justify-content-center">-->
<!--        <form method="post">-->
<!--          {% csrf_token %}-->
<!--          {{ u_form.as_p}}-->
<!--          {{ p_form.as_p}}-->
<!--          <button type="submit" class="btn btn-primary">Submit</button>-->
<!--        </form>-->
<!--      </div>-->
<!--    </div>-->

<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>-->
  </body>
{%endblock%}
</html>
















<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"-->
<!--         integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"-->
<!--         crossorigin="anonymous"></script>-->
<!--      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"-->
<!--         integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"-->
<!--         crossorigin="anonymous"></script>-->
<!--      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"-->
<!--         integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"-->
<!--         crossorigin="anonymous"></script>-->

EMART_pp/templates/home/search.html
<!DOCTYPE html> 
<html lang="en"> 
{%extends 'base.html'%} 
{%block baseblock%} 
<head> 
    <meta charset="UTF-8"> 
    <title>Title</title> 
</head><hr> 
<body> 
<div class = "container"> 
<div class="row"> 
   {% for product in search1 %} 
    <div class="card mx-auto mb-3" style="width: 10rem"> 
        <a href="/detail/{{product.id}}" class="btn"><div class="item"><img class="card-img-top" src="{{product.product_image.url}}"  alt="..."></div></a> 
  <div class="card-body"> 
    <h5 class="card-title">{{product.Product_brand}}</h5> 
    <p class="card-text">Rs. {{product.product_cost}}</p> 
  </div> 
</div> 
 
 
{%endfor%} 
</body> 
{%endblock%} 
</html>

EMART_pp/templates/home/signup.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
{%block baseblock%}
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<style>
    .helptext{display:none;}
</style>
<div class="container">
<body><center><h1>SIGN-UP PAGE</h1>
  <form method="POST" class="shadow p-5">
    {{form.as_p}}
    {%csrf_token%}
    <input type="submit">
<div class="test-center text-primary fw-bold">
    <small> Existing User to EMART World ?</small>
    <a href="/login" class="text-danger"> Login</a>
</div>
  </form>
</center>
</body>
    </div>
{%endblock%}
</html>